source 'https://rubygems.org'
if ENV['LOCALDEV']
  gem 'chef-provisioning-hanlon', path: '../chef-provisioning-hanlon'
  gem 'hanlon-api', path: '../hanlon-api-ruby'
else
  gem 'chef-provisioning-hanlon', github: 'hh/chef-provisioning-hanlon'
  gem 'hanlon-api', github: 'hh/hanlon-api-ruby'
end
gem 'libdevinput'
gem 'uuid'
gem 'base62'
gem 'colored'
gem 'bson'
# bson_ext is disabled to facilitate support of running Hanlon under jRuby.
gem 'bson_ext'
gem 'json'
gem 'net-ssh'
gem 'net-scp'
gem 'mongo', '~>1.12.0'
gem 'jdbc-postgres'
gem 'daemons'
gem 'logger'
gem 'grape'
gem 'grape-swagger'
gem 'facter'
gem 'rufus-scheduler'
gem 'warbler'
gem 'puma'
gem 'rubyipmi'

